# Generated by Django 5.0.6 on 2024-07-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_blog_likes_comments_blog_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='text',
            field=models.TextField(max_length=255, verbose_name='Comment'),
        ),
    ]
