# Generated by Django 5.0.6 on 2024-07-09 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_doctor_is_doctor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
