# Generated by Django 5.0.6 on 2024-07-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_appointment_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_visited',
            field=models.BooleanField(default=False),
        ),
    ]
